def is_key_pressed(ptr: int) -> bool: ...
def is_key_down(ptr: int) -> bool: ...
def is_key_released(ptr: int) -> bool: ...


def is_midi_preview() -> bool: ...
def send_midi_preview(): ...

def get_detail_clip() -> int: ...
def is_selected_track(ptr: int) -> bool: ...
def time_selection_start_time() -> float: ...
def time_selection_end_time() -> float: ...